
name: Build project and Run Lighthouse CI
on: [push]
jobs:
  lhci:
    name: Lighthouse CI
    runs-on: ubuntu-latest
    env: 
          -LHCI_GITHUB_APP_TOKEN: 9XvOj4HER7J:7422004:rv9iBeEaanxIr
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
          configPath: ./lighthouserc.json
          LHCI_GITHUB_APP_TOKEN: 9XvOj4HER7J:7422004:rv9iBeEaanxIr
      - name: npm install, build
        run: |
          npm install
          npm run build
      - name: run Lighthouse CI
        env:
          LHCI_GITHUB_APP_TOKEN: 9XvOj4HER7J:7422004:rv9iBeEaanxIr
        run: |
          npm install -g @lhci/cli@0.3.x
          npm install @lhci/server
          lhci autorun --assert.preset=lighthouse:all --LHCI_GITHUB_APP_TOKEN: 9XvOj4HER7J:7422004:rv9iBeEaanxIr --config=lighthouserc.json --collect.numberOfRuns=2 --upload.target=temporary-public-storage --upload.githubToken = 9XvOj4HER7J:7422004:rv9iBeEaanxIr --upload.githubAppToken = 9XvOj4HER7J:7422004:rv9iBeEaanxIr --githubAppToken = 9XvOj4HER7J:7422004:rv9iBeEaanxIr --githubToken = 9XvOj4HER7J:7422004:rv9iBeEaanxIr || echo "LHCI failed!"

